args2vars <- function(argList) {
  
  topconnect::clearAllDBcons()
  
  dbName <- NPO:::parseArg( args, 'service' )
  if ( nchar(dbName) == 0 ) {
    dbName <- NPO:::parseArg( args, 'dbName' )
    if ( nchar(dbName) == 0 ) {
      print( "Please provide a database name" )
    }
  }
  #print( dbName )
  hostname <- NPO:::parseArg( args, 'hostname' )
  if ( nchar(hostname) == 0 ) {
    hostname <- 'localhost'
  }
  password <- NPO:::parseArg( args, 'password' )
  if ( nchar(password) == 0 ) {
    password <- ''
  }
  db_user <- NPO:::parseArg( args, 'db_user' )
  if ( nchar(db_user) == 0 ) {
    db_user <- 'root'
  }
  
  #  conn <- topconnect::db( db_user="root", dbName=dbName, hostname=hostname, password=password )
  conn <- DBI::dbConnect( RMySQL::MySQL(), user=db_user, dbname=dbName, host=hostname, password=password )
  
  # Check that inputs are valid: have associated seizures, behavior and data.
  query <-paste0( "select * from behavior where subject= and ")
  
  # Evaluate the "tasks" table.
  #  print( 'Getting the context' )
  context <- topconnect::getContextFromTaskTable( conn, args )
  #  print( 'Getting parameters' )
  parameters <- NPO:::loadParameters( context )
  
  # Load the seizure times from the tasks table, which takes into account functions that identify "valid" seizures.
  # This table is generated by ...
  context <- NPO:::updateContextWithValidSeizureInformation( conn, context )
  #print( context )
  
  # Merge context and parameters into one list
  variables <- append( context, parameters )
  if ( "dbName" %in% names(variables) ) {
    variables$dbName <- dbName
  } else {
    variables <- append( variables, list(dbName=dbName) )
  }
  if ( "hostname" %in% names(variables) ) {
    variables$hostname <- hostname
  } else {
    variables <- append( variables, list(hostname=hostname) )
  }
  if ( "db_user" %in% names(variables) ) {
    variables$db_user <- db_user
  } else {
    variables <- append( variables, list(db_user=db_user) )
  }
  if ( "password" %in% names(variables) ) {
    variables$password <- password
  } else {
    variables <- append( variables, list(password=password) )
  }
  
  # Create database tables
  #  print( 'Creating tables' )
  #print( paste0( "NPO_window: context: correlationWindow: ", context$correlationWindow ) )
  #print( paste0( "NPO_window: context: CCthreshold: ", context$CCthreshold ) )
  table_names <- NPO:::createTablesForNPO( conn, variables )
  #  print( 'Tables created' )
  
  # I don't understand what the purpose of this function is. About the only useful thing is checking for a 'restart', which can be done on it's own.
  #  analysisPlan <- useArgsAndContextToPlan( conn, args, context )
  NPO:::checkRestart( args, conn, table_names, variables )
  NPO:::checkMEFpassword( variables ) # Make sure that the secret_vault has the correct password
  
  DBI::dbDisconnect( conn )

  return( variables )
}
