getFileMetadata <- function( conn, argComp ) {
  # Updates the arguments with case-specific information:
  # case-status, biological signal parameters, valid seizures,
  # creating tables, checking for a re-start and checking the MEF password
  #
  # From a section in "NPO_window.R"
  # Mark R. Bower
  # June 26, 2021
  # Yale University

  #  print( 'Getting the context' )
  context <- topconnect::getContextFromTaskTable( conn, argComp )
  #  print( 'Getting parameters' )
  parameters <- NPO:::loadParameters( context )
  
  # Load the seizure times from the tasks table, which takes into account functions that identify "valid" seizures.
  # This table is generated by ...
  context <- NPO:::updateContextWithValidSeizureInformation( conn, context )
  #print( context )
  
  # Create database tables
  #  print( 'Creating tables' )
  table_names <- NPO:::createTablesForNPO( conn, variables )
  #  print( 'Tables created' )
  
  # I don't understand what the purpose of this function is. About the only useful thing is checking for a 'restart', which can be done on it's own.
  NPO:::checkRestart( args, conn, table_names, variables )
  NPO:::checkMEFpassword( variables ) # Make sure that the secret_vault has the correct password}

  metadataInformer <- RFactories::metadataInformer( variables )
}
