install_my_packages <- function() {
  #invisible(lapply(paste0('package:', names(sessionInfo()$otherPkgs)), detach, character.only=TRUE, unload=TRUE))
  
  install.packages("DBI")
  install.packages("RMySQL")
  install.packages("devtools")
  install.packages("rJava")
  install.packages("Rcpp")
  install.packages("here")
  install.packages("GGally")
  install.packages("ggnetwork")
  install.packages("ggpubr")
  install.packages("Rfast")
  install.packages("reshape2")
  install.packages("R6")
  install.packages("R6P")
  library(devtools)
  devtools::install_github("markrbower/SingletonsInR", subdir="Analysis/SingletonsInR",upgrade=c("always"),force=TRUE)
  devtools::install_github("markrbower/topsecret", subdir="Analysis/topsecret",upgrade=c("always"),force=TRUE)
  devtools::install_github("markrbower/topconnect", subdir="Analysis/topconnect",upgrade=c("always"),force=TRUE)
  devtools::install_github("markrbower/topigraph", subdir="Analysis/topigraph",upgrade=c("always"),force=TRUE)
  devtools::install_github("markrbower/meftools", subdir="Analysis/meftools",upgrade=c("always"),force=TRUE)
  devtools::install_github("markrbower/NPO", subdir="Analysis/NPO",upgrade=c("always"),force=TRUE)
}
