NPO_window_v1 <- function(...) {
  # Network Properties Outlier
  # October 1, 2019
  # Mark R. Bower
  # Yale University
  #
  # create table tasks (nodename varchar(128),path varchar(256),data varchar(64),institution varchar(64),lab varchar(32),experiment varchar(32),subject int(11),signaltype varchar(32),iterationtype varchar(32),label varchar(512) not null,centerTime bigint,done boolean,created timestamp default current_timestamp, modified timestamp default current_timestamp on update current_timestamp, primary key (label) );
  #
  #' Run the Network Parameter Outlier (NPO) algorithm.
  #' 
  #' @export
  #' @examples
  #' \dontrun{
  #'   First time the function is called:
  #'   NPO_window(dbName='NSME_halo',path='NPO/Analysis/NPO/tests/testData/Halo/11',data='rodentMSO',institution='Yale',lab='NSME',experiment='Halo10sec_10x',subject=11,signalType='AP',centerTime=0,iterationType='directory',range=c(-3000,2000), '--restart' )
  #'
  #' ... or ...
  #' 
  #'   NPO_window(dbName='NV', path='/Users/markrbower/Dropbox/Documents/Concepts/2019_11_19_NetworkParameterOutlier/mef2', data='NV_23_002', institution='Yale', lab='NSME', experiment='baseline', subject='23_002', signalType='IIS', centerTime=0, iterationType='directory', range=c(-3000,2000), '--restart' )
  #' 
  #'   NPO_window(service='NV', path='/Users/markrbower/Documents/Data/NV/NVC1001_24_005_2', taskName='preprocessing', institution='Yale', lab='NSME', experiment='NeuroVista', subject='24_005', signalType='IIS', centerTime=0, iterationType='directory', range=c(-3000,2000), '--restart' )
  #' 
  #'   Subsequent calls:
  #'   NPO()
  #' }

  args <- list(...)

  setwd( here() )

  options(warn=-1)
  options(stringsAsFactors = FALSE);

  topconnect::clearAllDBcons()

  dbName <- NPO:::parseArg( args, 'service' )
  if ( nchar(dbName) == 0 ) {
    dbName <- NPO:::parseArg( args, 'dbName' )
    if ( nchar(dbName) == 0 ) {
      print( "Please provide a database name" )
    }
  }
  #print( dbName )
  hostname <- NPO:::parseArg( args, 'hostname' )
  if ( nchar(hostname) == 0 ) {
    hostname <- 'localhost'
  }
  password <- NPO:::parseArg( args, 'password' )
  if ( nchar(password) == 0 ) {
    password <- ''
  }
  db_user <- NPO:::parseArg( args, 'db_user' )
  if ( nchar(db_user) == 0 ) {
    db_user <- 'root'
  }
  
  #  conn <- topconnect::db( db_user="root", dbName=dbName, hostname=hostname, password=password )
  conn <- DBI::dbConnect( RMySQL::MySQL(), user=db_user, dbname=dbName, host=hostname, password=password )
  
  # Check that inputs are valid: have associated seizures, behavior and data.
  query <-paste0( "select * from behavior where subject= and ")
  
  # Evaluate the "tasks" table.
#  print( 'Getting the context' )
  context <- topconnect::getContextFromTaskTable( conn, args )
#  print( 'Getting parameters' )
  parameters <- NPO:::loadParameters( context )

  # Load the seizure times from the tasks table, which takes into account functions that identify "valid" seizures.
  # This table is generated by ...
  context <- NPO:::updateContextWithValidSeizureInformation( conn, context )
  #print( context )
  
  # Merge context and parameters into one list
  variables <- append( context, parameters )
  if ( "dbName" %in% names(variables) ) {
    variables$dbName <- dbName
  } else {
    variables <- append( variables, list(dbName=dbName) )
  }
  if ( "hostname" %in% names(variables) ) {
    variables$hostname <- hostname
  } else {
    variables <- append( variables, list(hostname=hostname) )
  }
  if ( "db_user" %in% names(variables) ) {
    variables$db_user <- db_user
  } else {
    variables <- append( variables, list(db_user=db_user) )
  }
  if ( "password" %in% names(variables) ) {
    variables$password <- password
  } else {
    variables <- append( variables, list(password=password) )
  }

  # Create database tables
#  print( 'Creating tables' )
  #print( paste0( "NPO_window: context: correlationWindow: ", context$correlationWindow ) )
  #print( paste0( "NPO_window: context: CCthreshold: ", context$CCthreshold ) )
  table_names <- NPO:::createTablesForNPO( conn, variables )
#  print( 'Tables created' )
  
  # I don't understand what the purpose of this function is. About the only useful thing is checking for a 'restart', which can be done on it's own.
  #  analysisPlan <- useArgsAndContextToPlan( conn, args, context )
  NPO:::checkRestart( args, conn, table_names, variables )
  NPO:::checkMEFpassword( variables ) # Make sure that the secret_vault has the correct password
  
  DBI::dbDisconnect( conn )
  # Find   the channel names and fill the progress table
  # Find peaks
  
  #print( paste0( "NPO_window: db_user: ", variables$db_user ) )
  
  NPO:::MEFthenAnalysisLoopOnDirectory( variables, dbName, table_names )
  
  # Find communities
#  MySQL_analysisLoop_P2M_batch( parameters, dbName, table_names, context )
  
  # Find clusters
  # MySQL_analysisLoop_M2C_batch( conn, '', table_names, subject, seizureTime )
  

}
