plotClusterWaveforms <- function( output, clusterid ) {
  # After timeVoltage2tibble.R
  # 'output' is generated by 'parallelWindowNPO' and is a list of vectors.
  #
  # Get the 'output' variable by running:
  #   load(file='output.RData')
  library( ggplot2 )
  library( reshape2 )
  library( plyr )
  library( tidyverse )
  
  if ( is.na(clusterid) ) {
    idx <- which( is.na(output$clusterid) )
  } else {
    idx <- which( output$clusterid == clusterid )
  }
  volt <- output$waveform[idx]

  df <- data.frame()
  N <- length( volt )
  for ( idx in seq(1,N) ) {
    if ( !is.null(volt[[idx]]) ) {
      df <- rbind( df, data.frame( g=rep(idx,7), x=seq(1,7), y=as.numeric( unlist(strsplit(volt[idx],',')) ) ) )
    }
  }

  #plot
  p <- df %>% ggplot( aes(x=x, y=y, group=g)) + geom_line(alpha=0.1) + labs(title = clusterid)
  print( p )
}

